# Generated by Django 3.2.13 on 2023-01-15 13:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_alter_chat_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='send_at',
            new_name='sent_at',
        ),
        migrations.AlterField(
            model_name='chat',
            name='users',
            field=models.ManyToManyField(related_name='chats', through='chat.UserChat', to=settings.AUTH_USER_MODEL),
        ),
    ]
