# Generated by Django 3.2.13 on 2023-04-30 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20230115_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(choices=[('chat', 'Chat'), ('channels', 'Channels')], max_length=300)),
                ('app_disable_reason', models.TextField()),
                ('estimated_recovery_time', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Блокировки приложений',
                'verbose_name_plural': 'Блокировка приложений',
            },
        ),
    ]
